grafana:
  adminPassword: "admin-change-me"
  service:
    type: ClusterIP

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1

prometheus:
  prometheusSpec:
    retention: 2d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
