apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-stateful
  namespace: dev
spec:
  serviceName: sample-stateful
  replicas: 1
  selector:
    matchLabels:
      app: sample-stateful
  template:
    metadata:
      labels:
        app: sample-stateful
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
