apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cloud-cost-advisor-allow-ingress
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: cloud-cost-advisor
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8080
